//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Siparis_Opsiyon
    {
        public int SiparisOpsiyon { get; set; }
        public int SiparisKey { get; set; }
        public int UrunOpsiyonTurKey { get; set; }
    
        public virtual Sipari Sipari { get; set; }
        public virtual T_Urun_Opsiyon_Tur T_Urun_Opsiyon_Tur { get; set; }
    }
}
