//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Siparis_Urun
    {
        public int SiparisUrunKey { get; set; }
        public int SiparisKey { get; set; }
        public int UrunKey { get; set; }
        public bool SiparisParca { get; set; }
        public bool SiparisOnay { get; set; }
        public bool SiparisMutfakTeslim { get; set; }
    
        public virtual Sipari Sipari { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
