//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genel_Ayar
    {
        public int GenelAyarKey { get; set; }
        public string GenelSirketAd { get; set; }
        public string GenelFaturaBilgi { get; set; }
        public string GenelFaturaMesaj { get; set; }
        public byte[] GenelSirketLogo { get; set; }
        public bool GenelMutfakKullanimi { get; set; }
        public bool GenelKdvDahil { get; set; }
        public byte GenelIndirimOran { get; set; }
        public byte[] GenelDefaultResim { get; set; }
    }
}
