//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Siparis = new HashSet<Sipari>();
            this.Siparis1 = new HashSet<Sipari>();
            this.Siparis2 = new HashSet<Sipari>();
        }
    
        public int KullaniciKey { get; set; }
        public Nullable<int> KullaniciTurKey { get; set; }
        public string KullaniciKullaniciAd { get; set; }
        public string KullaniciKullaniciParola { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public string KullaniciTcNo { get; set; }
        public string KullaniciSgkNo { get; set; }
        public System.DateTime KullaniciIseBaslamaTarihi { get; set; }
        public bool KullaniciSiparisIptalYetki { get; set; }
        public bool KullaniciUcretsizSatisYetki { get; set; }
        public bool KullaniciSabit { get; set; }
    
        public virtual Kullanici_Giris_Yetki Kullanici_Giris_Yetki { get; set; }
        public virtual T_Kullanici_Tur T_Kullanici_Tur { get; set; }
        public virtual ICollection<Sipari> Siparis { get; set; }
        public virtual ICollection<Sipari> Siparis1 { get; set; }
        public virtual ICollection<Sipari> Siparis2 { get; set; }
    }
}
