//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Giris_Yetki
    {
        public int KullaniciGirisYetkiKey { get; set; }
        public bool KullaniciGirisYetkiMasaSiparisYetki { get; set; }
        public bool KullaniciGirisYetkiPaketSiparisYetki { get; set; }
        public bool KullaniciGirisYetkiRezervasyonYetki { get; set; }
        public bool KullaniciGirisYetkiMusterilerYetki { get; set; }
        public bool KullaniciGirisYetkiMutfakYetki { get; set; }
        public bool KullaniciGirisYetkiKasaIslemleriYetki { get; set; }
        public bool KullaniciGirisYetkiRaporlarYetki { get; set; }
        public bool KullaniciGirisYetkiStokTakibiYetki { get; set; }
        public bool KullaniciGirisYetkiAyarlarYetki { get; set; }
        public bool KullaniciGirisYetkiTanimlamalarYetki { get; set; }
        public bool KullaniciGirisYetkiNotlarHatirlatmalarYetki { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
