//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIslemleri
    {
        public int LogKey { get; set; }
        public Nullable<int> KullaniciKey { get; set; }
        public System.DateTime IslemTarih { get; set; }
        public string YapilanIslem { get; set; }
        public string IslemIcerik { get; set; }
    }
}
