//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masa
    {
        public Masa()
        {
            this.Rezervasyon_Not_Hatirlatma = new HashSet<Rezervasyon_Not_Hatirlatma>();
            this.Siparis = new HashSet<Sipari>();
        }
    
        public int MasaKey { get; set; }
        public Nullable<int> MasaKatBolgeKey { get; set; }
        public string MasaNo { get; set; }
        public int MasaKisi { get; set; }
        public string MasaAciklama { get; set; }
        public bool MasaAcik { get; set; }
        public bool MasaAktif { get; set; }
        public byte MasaSira { get; set; }
    
        public virtual T_Masa_Kat_Bolge_Tur T_Masa_Kat_Bolge_Tur { get; set; }
        public virtual ICollection<Rezervasyon_Not_Hatirlatma> Rezervasyon_Not_Hatirlatma { get; set; }
        public virtual ICollection<Sipari> Siparis { get; set; }
    }
}
