//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.Siparis = new HashSet<Sipari>();
        }
    
        public int MusteriKey { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriUnvan { get; set; }
        public System.DateTime MusteriTarih { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAciklama { get; set; }
    
        public virtual ICollection<Sipari> Siparis { get; set; }
    }
}
