//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProCafeDBEntities : DbContext
    {
        public ProCafeDBEntities()
            : base("name=ProCafeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<A_Siparis_Opsiyon> A_Siparis_Opsiyon { get; set; }
        public DbSet<A_Siparis_Urun> A_Siparis_Urun { get; set; }
        public DbSet<A_Urun_Opsiyon> A_Urun_Opsiyon { get; set; }
        public DbSet<Genel_Ayar> Genel_Ayar { get; set; }
        public DbSet<Kullanici> Kullanicis { get; set; }
        public DbSet<Kullanici_Giris_Yetki> Kullanici_Giris_Yetki { get; set; }
        public DbSet<LogIslemleri> LogIslemleris { get; set; }
        public DbSet<Masa> Masas { get; set; }
        public DbSet<Musteri> Musteris { get; set; }
        public DbSet<Rezervasyon_Not_Hatirlatma> Rezervasyon_Not_Hatirlatma { get; set; }
        public DbSet<Sipari> Siparis { get; set; }
        public DbSet<T_Kullanici_Tur> T_Kullanici_Tur { get; set; }
        public DbSet<T_Masa_Kat_Bolge_Tur> T_Masa_Kat_Bolge_Tur { get; set; }
        public DbSet<T_Urun_Kategori_Tur> T_Urun_Kategori_Tur { get; set; }
        public DbSet<T_Urun_Opsiyon_Tur> T_Urun_Opsiyon_Tur { get; set; }
        public DbSet<Urun> Uruns { get; set; }
    }
}
