//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon_Not_Hatirlatma
    {
        public int RezervasyonNotHatirlatmaKey { get; set; }
        public Nullable<int> MasaKey { get; set; }
        public bool RezervasyonNotHatirlatmaTip { get; set; }
        public System.DateTime RezervasyonNotHatirlatmaTarihSaat { get; set; }
        public string RezervasyonNotHatirlatmaAciklama { get; set; }
    
        public virtual Masa Masa { get; set; }
    }
}
