//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        public Sipari()
        {
            this.A_Siparis_Opsiyon = new HashSet<A_Siparis_Opsiyon>();
            this.A_Siparis_Urun = new HashSet<A_Siparis_Urun>();
        }
    
        public int SiparisKey { get; set; }
        public Nullable<int> MasaKey { get; set; }
        public Nullable<int> SiparisiAlanKullaniciKey { get; set; }
        public Nullable<int> MutfakOnayKullaniciKey { get; set; }
        public Nullable<int> KasaOdemeKullaniciKey { get; set; }
        public Nullable<int> MusteriKey { get; set; }
        public System.DateTime SiparisAlindiTarih { get; set; }
        public Nullable<System.DateTime> SiparisMutfakOnayTarih { get; set; }
        public Nullable<System.DateTime> SiparisHesapKapatildiTarih { get; set; }
        public decimal SiparisToplam { get; set; }
        public decimal SiparisOdenen { get; set; }
        public string SiparisAd { get; set; }
        public string SiparisSoyad { get; set; }
        public string SiparisTelefon { get; set; }
        public string SiparisAdres { get; set; }
        public string SiparisAciklama { get; set; }
        public bool SiparisYazildi { get; set; }
        public bool SiparisIptal { get; set; }
        public bool SiparisUcretsizKapatma { get; set; }
        public bool SiparisParcali { get; set; }
    
        public virtual ICollection<A_Siparis_Opsiyon> A_Siparis_Opsiyon { get; set; }
        public virtual ICollection<A_Siparis_Urun> A_Siparis_Urun { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Kullanici Kullanici2 { get; set; }
        public virtual Masa Masa { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
