//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Kullanici_Tur
    {
        public T_Kullanici_Tur()
        {
            this.Kullanicis = new HashSet<Kullanici>();
            this.Uruns = new HashSet<Urun>();
        }
    
        public int KullaniciTurKey { get; set; }
        public string KullaniciTurAd { get; set; }
    
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
        public virtual ICollection<Urun> Uruns { get; set; }
    }
}
