//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Masa_Kat_Bolge_Tur
    {
        public T_Masa_Kat_Bolge_Tur()
        {
            this.Masas = new HashSet<Masa>();
        }
    
        public int MasaKatBolgeKey { get; set; }
        public string MasaKatBolgeAd { get; set; }
    
        public virtual ICollection<Masa> Masas { get; set; }
    }
}
