//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Urun_Kategori_Tur
    {
        public T_Urun_Kategori_Tur()
        {
            this.Uruns = new HashSet<Urun>();
        }
    
        public int UrunKategoriTurKey { get; set; }
        public string UrunKategoriTurAd { get; set; }
        public byte[] UrunKategoriResim { get; set; }
        public int UrunKategoriTurSiralama { get; set; }
    
        public virtual ICollection<Urun> Uruns { get; set; }
    }
}
