//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Urun_Opsiyon_Tur
    {
        public T_Urun_Opsiyon_Tur()
        {
            this.A_Siparis_Opsiyon = new HashSet<A_Siparis_Opsiyon>();
            this.A_Urun_Opsiyon = new HashSet<A_Urun_Opsiyon>();
        }
    
        public int UrunOpsiyonTurKey { get; set; }
        public string UrunOpsiyonAd { get; set; }
    
        public virtual ICollection<A_Siparis_Opsiyon> A_Siparis_Opsiyon { get; set; }
        public virtual ICollection<A_Urun_Opsiyon> A_Urun_Opsiyon { get; set; }
    }
}
