//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public Urun()
        {
            this.A_Siparis_Urun = new HashSet<A_Siparis_Urun>();
            this.A_Urun_Opsiyon = new HashSet<A_Urun_Opsiyon>();
        }
    
        public int UrunKey { get; set; }
        public int UrunKategoriTurKey { get; set; }
        public Nullable<int> KullaniciTurKey { get; set; }
        public string UrunAd { get; set; }
        public decimal UrunFiyat { get; set; }
        public int UrunSiralama { get; set; }
        public string UrunAciklama { get; set; }
        public bool UrunAktif { get; set; }
    
        public virtual ICollection<A_Siparis_Urun> A_Siparis_Urun { get; set; }
        public virtual ICollection<A_Urun_Opsiyon> A_Urun_Opsiyon { get; set; }
        public virtual T_Kullanici_Tur T_Kullanici_Tur { get; set; }
        public virtual T_Urun_Kategori_Tur T_Urun_Kategori_Tur { get; set; }
    }
}
