//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Program {
    
    
    public partial class Program_Rezervasyon {
        
        /// <summary>
        /// Rezervasyon_Not_Hatirlatma_User_Control1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProCafe.UserControl.Rezervasyon_Not_Hatirlatma_User_Control Rezervasyon_Not_Hatirlatma_User_Control1;
    }
}
