//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCafe.Program {
    
    
    public partial class Program_Mutfak {
        
        /// <summary>
        /// Kasa_Mutfak_User_ControlProgramMutfak control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProCafe.UserControl.Kasa_Mutfak_User_Control Kasa_Mutfak_User_ControlProgramMutfak;
    }
}
